pages setup hotfix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,7 +18,7 @@ concurrency:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
 
     environment:
       name: github-pages
@@ -31,7 +31,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v7
         with:
-          node-version: 24
+          node-version: 26
           cache: npm
 
       - name: Setup Rust nightly
@@ -39,10 +39,32 @@ jobs:
         with:
           targets: wasm32-unknown-unknown
 
+      - name: Install rust-lld
+        shell: pwsh
+        run: |
+          rustup component add llvm-tools-preview
+
+          $sysroot = rustc --print sysroot
+          $llvmBin = Join-Path $sysroot "lib\rustlib\x86_64-pc-windows-msvc\bin"
+
+          Write-Host "Rust LLVM directory:"
+          Write-Host $llvmBin
+
+          $rustLld = Join-Path $llvmBin "rust-lld.exe"
+
+          if (-not (Test-Path $rustLld)) {
+              Write-Error "rust-lld.exe was not found at $rustLld"
+              exit 1
+          }
+
+          Write-Host "Found rust-lld"
+          Write-Host $rustLld
+
       - name: Install wasm-pack
         run: cargo install wasm-pack --locked --version 0.15.0
 
-      - name: Check toolchain
+      - name: Verify toolchain
+        shell: pwsh
         run: |
           node --version
           npm --version
